CREATE TABLE users (
id NUMBER GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL PRIMARY KEY ,
username VARCHAR2(255) NOT NULL,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
password_hash VARCHAR2(255) NOT NULL,
password_salt VARCHAR2(255) NOT NULL,
security_question VARCHAR2(255) NOT NULL,
security_answer VARCHAR2(255) NOT NULL
);


CREATE TABLE tags (
id NUMBER GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL PRIMARY KEY,
name VARCHAR2(255) NOT NULL,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
CONSTRAINT uc_tags_name UNIQUE (name)
);

CREATE TABLE posts (
id NUMBER GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL PRIMARY KEY,
user_id NUMBER,
title VARCHAR2(255) NOT NULL,
content CLOB NOT NULL,
code_content CLOB ,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
CONSTRAINT fk_posts_user FOREIGN KEY (user_id) REFERENCES users (id)
);

create table post_tag(
post_id NUMBER,
tag_id NUMBER,
CONSTRAINT fk_post_tag_pid FOREIGN KEY (post_id) REFERENCES posts (id),
CONSTRAINT fk_posts_tag_tid FOREIGN KEY (tag_id) REFERENCES tags (id)
);

CREATE TABLE comments (
id NUMBER GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL PRIMARY KEY,
post_id NUMBER,
content CLOB NOT NULL,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
CONSTRAINT fk_comments_post FOREIGN KEY (post_id) REFERENCES posts (id)
);